# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a35a2e500fe333b7b3ee4b083c0c441a6520ea5071a3ea33324c07b20b127913c56860a3633324dbc50d199e16a5657e9dd57d0170769fe8239a419d2935c0

test:
  secret_key_base: ed6daf02325017c32767f0af0eae98a07162664acb7bd6bb40fd4a3ceec4f5f7e40b807953ff2e613b503d1817a37083b3f8d775d0b5bd93b297812c399c8e89

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
